finished task3, started task4
jlheig/SER-LAB4 pull request #1
Opened 2021-06-01 13:53 UTC by jlheig

2021-06-02 10:03 UTC, roosemberth requested changes
Thanks for the patch, please mind the remarks attached to this review.

Please try to split each step in a different commit. Whilst it may not be necessary for this collaboration, it's better if you get yourself used to committing rather frequently. There's no need to reorganize the commits in this branch.

You may amend your commit and push-force or create and push a commit on top of this branch at your convenience.

2021-06-02 10:03 UTC, roosemberth commented on pokedex.xsl
> +	/> <!-- ##### A compléter 1 -->
```suggestion
	/>
```

2021-06-02 10:03 UTC, roosemberth commented on pokedex.xsl
> +						<xsl:variable name="types" select="distinct-values(//pokedex/pokemon/@type)" /> <!-- ##### A compléter 3 : Ici, vous devez trouver l'expression XPath à mettre dans l'attribut select
Please remove the stray handout comment.

2021-06-02 10:03 UTC, roosemberth commented on pokedex.xsl
>  								<!-- ##### A compléter 4 : Ici, vous devez faire appel au template lister_pokemon en lui passant le bon filtre en paramètre -->
```suggestion
```

2021-06-02 10:03 UTC, roosemberth commented on pokedex.xsl
> +	</xsl:template>> <!-- Fin a compléter 2 -->
```suggestion
	</xsl:template>>
```

2021-06-02 10:03 UTC, roosemberth commented on pokedex.xsl
> +	</xsl:template>> <!-- Fin a compléter 2 -->
```suggestion
	</xsl:template>
```

Closing tag seems to have an extra `>`. Please remove handout comments.

2021-06-08 12:42 UTC, closed without merging

2021-06-08 12:42 UTC, jlheig commented
Decided to delete everything and start again from scartch because the stuff I did wasn't adequate